% When working locally      Comp = 1
% When working on Server    Comp = 2
% When working on Castles   Comp = 3

Comp = 2;
switch Comp
    case 1
        Basepath = 'Z:\RDS\';
    case 2
        Basepath = '\\analyse4/Project0304/RDS/';
    case 3 % Cluster
        Basepath = '/analyse/Project0304/RDS/';
end 
addpath(...
    [Basepath, 'Mircea/Tools/fieldtrip-20230118'], ...
    [Basepath, 'Common/tools'], ...
    genpath([Basepath, 'Mircea/3 - SPES/Analysis']),...
    genpath([Basepath, 'Mircea/Tools/wave_clus-3']),...  
    genpath([Basepath, 'Mircea/Tools/LittleScripts']),...
    genpath([Basepath, 'Mircea/Tools/NlxWindowsRead']),...
    genpath([Basepath, 'Mircea/Tools/fooof/mat_py_mat-master/mat_py_mat-master/utils']),...
    genpath([Basepath, 'Mircea/FvPS/Scripts']),...
    genpath([Basepath, 'Mircea/Tools/CircStat']),...
    genpath([Basepath, 'Mircea/Tools/MNI2Ctx']),...
    genpath([Basepath, 'Mircea/Tools/NIfTI_20140122']),...
    genpath([Basepath, 'Mircea/Tools/phasemap']),...
    genpath([Basepath, 'Mircea/Tools/RainCloudPlots']))

ft_defaults
cd([Basepath, 'Mircea/3 - SPES/Datasaves'])

clear Comp
%genpath([Basepath, 'Common/releaseDec2015']),...