if subjID(1:3) == 'P07';
    IC.label = {
        'Events'
        'ROF_1';
        'ROF_2';
        'ROF_3';
        'ROF_4';
        'ROF_5';
        'ROF_6';
        'ROF_7';
        'ROF_8';
        'ROF_9';
        'ROF_10';
        'R FI_1';
        'R FI_2';
        'R FI_3';
        'R FI_4';
        'R FI_5';
        'R FI_6';
        'R FI_7';
        'R FI_8';
        'R FI_9';
        'R FI_10';
        'R FI_11';
        'R FI_12';
        'R AH_1';
        'R AH_2';
        'R AH_3';
        'R AH_4';
        'R AH_5';
        'R AH_6';
        'R AH_7';
        'R AH_8';
        'R MH_1';
        'R MH_2';
        'R MH_3';
        'R MH_4';
        'R MH_5';
        'R MH_6';
        'R MH_7';
        'R MH_8';
        'R PH_1';
        'R PH_2';
        'R PH_3';
        'R PH_4';
        'R PH_5';
        'R PH_6';
        'R PH_7';
        'R PH_8';
        'R P as_1';
        'R P as_2';
        'R P as_3';
        'R P as_4';
        'R P as_5';
        'R P as_6';
        'R P as_7';
        'R P as_8';
        'R P ps_1';
        'R P ps_2';
        'R P ps_3';
        'R P ps_4';
        'R P ps_5';
        'R P ps_6';
        'R P ps_7';
        'R P ps_8';
        'C63';
        'C64';
        'R O ai_1';
        'R O ai_2';
        'R O ai_3';
        'R O ai_4';
        'R O ai_5';
        'R O ai_6';
        'R O ai_7';
        'R O ai_8';
        'R O pi_1';
        'R O pi_2';
        'R O pi_3';
        'R O pi_4';
        'R O pi_5';
        'R O pi_6';
        'R O pi_7';
        'R O pi_8';
        'R C_1';
        'R C_2';
        'R C_3';
        'R C_4';
        'R C_5';
        'R C_6';
        'R C_7';
        'R C_8';
        'L FI_1';
        'L FI_2';
        'L FI_3';
        'L FI_4';
        'L FI_5';
        'L FI_6';
        'L FI_7';
        'L FI_8';
        'L FI_9';
        'L FI_10';
        'L FI_11';
        'L FI_12';
        'L MH_1';
        'L MH_2';
        'L MH_3';
        'L MH_4';
        'L MH_5';
        'L MH_6';
        'L MH_7';
        'L MH_8';
        'LPO_1';
        'LPO_2';
        'LPO_3';
        'LPO_4';
        'LPO_5';
        'LPO_6';
        'LPO_7';
        'LPO_8';
        'C117';
        'C118';
        'C119';
        'C120';
        'C121';
        'C122';
        'C123';
        'C124';
        'C125';
        'C126';
        'C127';
        'C128';
        'C129';
        'C130';
        'C131';
        'C132';
        'C133';
        'C134';
        'C135';
        'C136';
        'C137';
        'C138';
        'C139';
        'C140';
        'U1';
        'U2';
        'U3';
        'U4';
        'U5';
        'U6';
        'U7';
        'U8';
        };
elseif subjID(1:3) == 'P10';
    IC.label = {
        'Events'
        'R AH_1';
        'R AH_2';
        'R AH_3';
        'R AH_4';
        'R AH_5';
        'R AH_6';
        'R AH_7';
        'R AH_8';
        'R MH_1';
        'R MH_2';
        'R MH_3';
        'R MH_4';
        'R MH_5';
        'R MH_6';
        'R MH_7';
        'R MH_8';
        'R PH_1';
        'R PH_2';
        'R PH_3';
        'R PH_4';
        'R PH_5';
        'R PH_6';
        'R PH_7';
        'R PH_8';
        'R PHG_1';
        'R PHG_2';
        'R PHG_3';
        'R PHG_4';
        'R PHG_5';
        'R PHG_6';
        'R PHG_7';
        'R PHG_8';
        'L AH_1';
        'L AH_2';
        'L AH_3';
        'L AH_4';
        'L AH_5';
        'L AH_6';
        'L AH_7';
        'L AH_8';
        'L MH_1';
        'L MH_2';
        'L MH_3';
        'L MH_4';
        'L MH_5';
        'L MH_6';
        'L MH_7';
        'L MH_8';
        'L PH_1';
        'L PH_2';
        'L PH_3';
        'L PH_4';
        'L PH_5';
        'L PH_6';
        'L PH_7';
        'L PH_8';
        'L PHG_1';
        'L PHG_2';
        'L PHG_3';
        'L PHG_4';
        'L PHG_5';
        'L PHG_6';
        'L PHG_7';
        'L PHG_8';
        'Unknown_1';
        'Unknown_2';
        'Unknown_3';
        'Unknown_4';
        'Unknown_5';
        'Unknown_6';
        'Unknown_7';
        'Unknown_8';
        'Unknown_9';
        'Unknown_10';
        'Unknown_11';
        'Unknown_12';
        'Unknown_13';
        'Unknown_14';
        'Unknown_15';
        'Unknown_16';
        'Unknown_17';
        'Unknown_18';
        'Unknown_19';
        'Unknown_20';
        'Unknown_21';
        'Unknown_22';
        'Unknown_23';
        'Unknown_24';
        'Unknown_25';
        'Unknown_25';
        'Unknown_26';
        'Unknown_27';
        'Unknown_28';
        'Unknown_29';
        'Unknown_30';
        'Unknown_31';
        'Unknown_32';
        'Unknown_33';
        'Unknown_34';
        'Unknown_35';
        'Unknown_36';
        'Unknown_37';
        'Unknown_38';
        'Unknown_39';
        'Unknown_40';
        'Unknown_41';
        'Unknown_42';
        'Unknown_43';
        'Unknown_44';
        'Unknown_45';
        'Unknown_46';
        'Unknown_47';
        'Unknown_48';
        'Unknown_49';
        'Unknown_50';
        'Unknown_51';
        'Unknown_52';
        'Unknown_53';
        'Unknown_54';
        'Unknown_55';
        'Unknown_56';
        'Unknown_57';
        'Unknown_58';
        'Unknown_59';
        'Unknown_60';
        'Unknown_61';
        'Unknown_62';
        'Unknown_63';
        'Unknown_64';
        'Unknown_65';
        'Unknown_66';
        'Unknown_67';
        'Unknown_68';
        'Unknown_69';
        'Unknown_70';
        'Unknown_71';
        'Unknown_72';
        'Unknown_73';
        'Unknown_74';
        'Unknown_75';
        'Unknown_76';
        'Unknown_77';
        'Unknown_78';
        'Unknown_79';
        'TRIG';
        'SpO2';
        'PR';
        'Pleth'
        };
elseif subjID(1:3) == 'P11';
    load([Basepath, 'Mircea/Datasaves/Macro/P11/P13_DB_Quantum_16KHz_Day1_signalHeader.mat'])
    for x = 1:length(signalHeader)
        IC.label{x,1} = signalHeader(1,x).signal_labels;        
    end
    clear signalHeader
end